ticket 2073: add simple test for method IO.copyDirectory()
playframework/play1 pull request #1075
Opened 2016-12-29 23:34 UTC by asolntsev

just a simple test showing that IO.copyDirectory() works as expected

(see ticket https://play.lighthouseapp.com/projects/57987/tickets/2073)

2017-01-03 03:54 UTC, xael-fry commented
new test is failling
```
Testsuite: play.libs.IOTest
Tests run: 1, Failures: 1, Errors: 0, Time elapsed: 0.003 sec
Testcase: copyDirectory_copiesFilesWithSpecialCharacterInName(play.libs.IOTest):	FAILED
 junit.framework.AssertionFailedError
at play.libs.IOTest.copyDirectory_copiesFilesWithSpecialCharacterInName(IOTest.java:19)
Test play.libs.IOTest FAILED
```

2017-01-03 03:54 UTC, xael-fry requested changes
new test is failling
```
Testsuite: play.libs.IOTest
Tests run: 1, Failures: 1, Errors: 0, Time elapsed: 0.003 sec
Testcase: copyDirectory_copiesFilesWithSpecialCharacterInName(play.libs.IOTest):	FAILED
 junit.framework.AssertionFailedError
at play.libs.IOTest.copyDirectory_copiesFilesWithSpecialCharacterInName(IOTest.java:19)
Test play.libs.IOTest FAILED
```

2017-01-17 14:23 UTC, flybyray commented
maybe you check again #1041 it is related to os language settings.
local test work if you have a LANG environment set but if you `unset LANG` it will fail.
the tests on travis run without LANG therefore it will fail there too.

it is related to:
http://stackoverflow.com/questions/5663709/how-to-fix-java-when-if-refused-to-open-a-file-with-special-charater-in-filename
http://stackoverflow.com/questions/3072376/how-can-i-open-files-containing-accents-in-java

the problem of the play framework library play.libs.IO is the 
`for (String child: source.list()) {`
the string `child` gets wrong file name because of encoding problems.
my solution was not to rely on encoding at all, using the filetree walker of java. it suits best the recursive copying of the library.

therefore check again #1041 before releasing 1.4.4 play

2025-11-15 11:22 UTC, aleksandy commented
@xael-fry, this PR may be closed too. The test was added in #1488 .

2026-05-11 10:22 UTC, closed without merging